import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './styles/global.css'
import App from './App'

 --- NEW CODE START --
// 1. Import the SVG so Vite processes and hashes it
import favicon from '.assets/favicon.svg'

// 2. Dynamically update the favicon in the <head>
const updateFavicon = () => {
  // Look for an existing favicon link, or create a new one
  let link = document.querySelector<HTMLLinkElement>("link[rel*='icon']");
  
  if (!link) {
    link = document.createElement('link');
    document.head.appendChild(link);
  }
  
  link.type = 'image/svg+xml';
  link.rel = 'icon';
  link.href = favicon; // This uses the unique hashed URL generated by Vite
};

// Run the function immediately when the app loads
updateFavicon();
// --- NEW CODE END ---

// Your existing React render code
createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
